### ISSUE TITLE
Add support for Nexmo Short Codes

### ISSUE THREAD

**Issue by jolamar** [laravel/nexmo-notification-channel#13]
https://www.nexmo.com/platform/short-codes
developer docs: https://developer.nexmo.com/messaging/us-short-codes/guides/alerts/php

Currently all SMS messages from Nexmo have a phone number. I want to be able to use their Short Code API so messages could come from a short code like `888-111`

![image](https://user-images.githubusercontent.com/1017119/60998051-78552f00-a315-11e9-979f-51877b5b6df5.png)

**Comment by jolamar** [comment]
<img width="574" alt="Screen Shot 2019-07-10 at 1 48 11 PM" src="https://user-images.githubusercontent.com/1017119/60999889-72614d00-a319-11e9-8eb3-b5b2fe9ecd60.png">

There are two types of short codes:

1. 2FA 
2. Alerts

Here is the API call for alerts: https://rest.nexmo.com/sc/us/alert/json?api_key={$your_key}&api_secret={$your_secret}&to={$to}&key1={$value1}&key2={$value2}

**Comment by driesvints** [comment]
Feel free to send in a PR that doesn't breaks too much.

**Comment by driesvints** [comment]
This was merged a while ago
