### ISSUE TITLE
Using Nexmo API Response

### ISSUE THREAD

**Issue by Braunson** [laravel/nexmo-notification-channel#16]
I'm looking to use the response from the Nexmo API `send()` call but can't seem to figure a way to hook into it from inside the Notification itself.

The only option is the event `NotificationSent` possibly. I was hoping to specifically catch the response inside the Notification but the more I look it doesn't seem ideal/possible and events are the way to go.

**Comment by awebartisan** [comment]
Hey @Braunson , were you able to solve this via `NotificationSent` event?

I get the `Nexmo\Message\Message` object in `$event->response` but unable to call methods on this object. I get `stream` errors from `Psr7/Guzzle` library whenever I call a `get` method on this `Message` object. For example,

`$event->response->getStatus();` 

Do I need to initialise this object again somehow?

**Comment by bhojkapderas** [comment]
@awebartisan did you ever figure this out? I have the same issue.
