### ISSUE TITLE
Model routing method without error

### ISSUE THREAD

**Issue by FreemanPrey** [laravel/nexmo-notification-channel#31]
- Nexmo Notification Channel Version: 2.3
- Laravel Version: 6.2
- PHP Version: 7.4

### Description:
In the official documentation describe one [step](https://laravel.com/docs/6.x/notifications#routing-sms-notifications) of installation. If (in any reason) we miss it and try to send sms we haven't any errors, sending just not working.
Method **send** of NexmoSmsChannel class has next block:

``` 
if (! $to = $notifiable->routeNotificationFor('nexmo', $notification)) {
    return;
}
```
If you just forgot to add to eloquent model **routeNotificationForNexmo** method attempt to send sms returned without any masseges. I think instead _return_ must be _exception_.

**Comment by driesvints** [comment]
You can do this in the routeNotificationForNexmo in your model yourself if you wish. This is just a convenience for when a user hasn't defined a phone number yet so it doesn't sends an sms.

**Comment by FreemanPrey** [comment]
So, why try to send sms for user without phone ? If user have phone field set of null (or haven't field himself) can method `routeNotificationForNexmo` return value of null ?
How I can see, `NexmoSmsChannel::send` method in `if` block must to execute return again.
But if in any reason user model haven't method `routeNotificationForNexmo` more “developer friendly” would be throw exception (smth like MethodNotFoundException), as I think.
