### ISSUE TITLE
Package zendframework/zend-diactoros is abandoned, you should avoid using it. Use laminas/laminas-diactoros instead.

### ISSUE THREAD

**Issue by Nothing-Works** [laravel/nexmo-notification-channel#32]
- Nexmo Notification Channel Version: 2.3.0
- Laravel Version: 6.14.0
- PHP Version: 7.4.1
- Database Driver & Version:

Package zendframework/zend-diactoros is abandoned, you should avoid using it. Use laminas/laminas-diactoros instead.

Does anyone have this issue? I got this when I am installing the package.

**Comment by lornajane** [comment]
You will see this warning until we replace the package names in the `nexmo-php` package. You can follow along with progress on that issue over here: https://github.com/Nexmo/nexmo-php/issues/206

**Comment by driesvints** [comment]
Hey @Nothing-Works. Please see the link above. Thanks @lornajane
