### ISSUE TITLE
Stream not rewinding after receiving Nexmo Message response in NotificationSent listener

### ISSUE THREAD

**Issue by awebartisan** [laravel/nexmo-notification-channel#35]
- Nexmo Notification Channel Version: ^2.3
- Laravel Version: 7.6.1
- PHP Version: 7.4.2
- Database Driver & Version: MySQL 5.7 + Redis v5.0.3 (using **predis**)
- Queue Connection: Redis
### Description:
I am sending SMS using Nexmo and `laravel/nexmo-notification-channel`. I want to use the response that gets back from Nexmo.

Laravel provides a nice **NotificationSent** event, for which we can register a listener and access the **response** using `$event->response` inside the handle function and we get `Nexmo\Message\Message` object.

This works fine. But it doesn't work when we Queue the Notification and `NotificationSentListener`. I get following exception when I call **any method** on `Nexmo\Message\Message` object.

`$event->response->getStatus();` throws:

`ErrorException: fseek() expects parameter 1 to be resource, int given in /Users/zubairmohsin/sites/sitename/vendor/guzzlehttp/psr7/src/Stream.php:204`

#### Stacktrace:
```
#1 /Users/zubairmohsin/sites/sitename/vendor/guzzlehttp/psr7/src/Stream.php(204): fseek(0, 0, 0)
--
#2 /Users/zubairmohsin/sites/sitename/vendor/guzzlehttp/psr7/src/Stream.php(190): GuzzleHttp\Psr7\Stream->seek(0)
#3 /Users/zubairmohsin/sites/sitename/vendor/nexmo/client-core/src/Entity/JsonResponseTrait.php(29): GuzzleHttp\Psr7\Stream->rewind()
#4 /Users/zubairmohsin/sites/sitename/app/Domain/SMS/Listeners/MessageSent.php(36): Nexmo\Message\Message->getResponseData()
#5 [internal function]: App\Domain\SMS\Listeners\MessageSent->handle(Object(Illuminate\Notifications\Events\NotificationSent))
```

### Steps To Reproduce:
- Fresh Laravel project with Queue connection set to Redis ( I am using Laravel Horizon )
- Setup Nexmo account and API keys
- composer require laravel/nexmo-notification-channel
- Send a TestNotification on Nexmo channel
- Register `NotificationSent` event and its listener `NotificationSentListener`
- Queue `NotificationSentListener`
- Inside handle method:
```php
$nexmoMessage = $event->response;

$nexmoMessage->getStatus();
```

### Findings
Working with @dragonmantank , we found out that this issue happens because **response** is a stream. It can't be serialised therefore queueing causes it to disappear. Patch is required in **laravel/nexmo-notification-channel** which will always turn that into a string instead of leaving it as a resource. You can read full discussion here: [https://github.com/Nexmo/nexmo-php/issues/219](https://github.com/Nexmo/nexmo-php/issues/219)

**Comment by driesvints** [comment]
Thanks for reporting this. If you can, appreciating a PR for this.

**Comment by awebartisan** [comment]
Tried to find more about it but I guess its beyond me 😞

When Laravel dispatches `NotificationSent` event inside `Illuminate\Notification\NotificationSender` line 149, `$response` is of type `Nexmo\Message\Message`. It has a protected property of `#response` which comes from `\Nexmo\Entity\Psr7Trait`. It looks like below:

![image](https://user-images.githubusercontent.com/29105478/79491631-2ece0900-8038-11ea-9b6e-105764fa9018.png)

`#response` contains a  private `stream` property. Since the Listener is **queued**, all of this will be **serialized**.  `stream` exists as a nested property inside `Message` object and its a **resource**. We will loose this stream while serializing if we don't keep a reference to it. 

Since this is a nested property inside an object, I am not sure how to deal with this.

- Is this something that needs to be fixed on **nexmo-php** side?
- Or maybe inside `SerializeModels` trait to  check all properties and even nested properties to see if they have `resource` type property,  store reference to `resource` while pushing to queue?
- It sure doesn't seem like a bug in this channel package 🤷🏻‍♂️

Let me know your thoughts on this please.

**Comment by dragonmantank** [comment]
* I'm looking to see what the impact of changing that from directly using the resource to always translating that to a string is
* If it's too much of an impact, we might change this to have the behavior serialize this to a string instead of leaving it as a resource

I agree it's not technically a bug (it's all working as written, and only has an issue with queues). So Nexmo is actively aware of it, and will either provide a PR here or let you know that we'll take care of it on our end.

**Comment by driesvints** [comment]
@dragonmantank awesome, thanks a lot Chris! :)
