### ISSUE TITLE
Problem with client_ref (probably should be named client-ref)

### ISSUE THREAD

**Issue by kodooy** [laravel/nexmo-notification-channel#43]
- Nexmo Notification Channel Version: 2.5
- Laravel Version: 8.18.1
- PHP Version: 7.4.10

### Description:

When I'm sending NexmoMessage with clientReference() method a 'client_ref' parameter is added to my request, but according to Nexmo documentation this parameter should be called 'client-ref' (https://developer.nexmo.com/messaging/sms/guides/delivery-receipts#using-the-sms-api-in-campaigns). 

With 'client_ref' parameter I have got an error 'Undefined index: client_ref' in payload I receive from Nexmo.
When I change in src/Channels/NexmoSmsChannel.php file 'client_ref' into 'client-ref' (line: 62 i 66) everything works OK (there is 'client-ref' property in payload form Nexmo).

### Steps To Reproduce:

```
public function toNexmo($notifiable)
{
     return (new NexmoMessage)
            ->content($this->message->body)
            ->unicode()
            ->clientReference($this->message->id);
}
```

**Comment by driesvints** [comment]
I'm confused myself here. It strikes me as odd that @Braunson wouldn't have tested his own implementation or anyone wouldn't have reported this before. Did something change on Nexmo's part or in one of the third party Nemxo libraries?

Original PR: https://github.com/laravel/nexmo-notification-channel/pull/17

/cc @Braunson @dragonmantank

**Comment by Braunson** [comment]
@driesvints It certainly is `client-ref` on the Nexmo docs, I don't see any versioning option for the docs if it did change to go back and see. Perhaps I had client-ref locally but with the underscore in the PR somehow, an oversight on my part. I've put in a new PR to resolve this issue.

I did find this https://metacpan.org/pod/Nexmo::SMS::Response::Message which references `client_ref` back in 1.x 🤷‍♂️

While I did run a quick test in the Nexmo sandbox and wasn't able to re-create that specific error from @kodooy, I did notice `client_ref` wasn't being returned where-as when I changed it to `client-ref` it was.

```
# With client-ref
[2020-12-21 14:33:59] local.ERROR: array (
  'msisdn' => '1xxxxxxxxxx',
  'to' => '1xxxxxxxxxx',
  // ...
  'client-ref' => 'abc-1234',
  'message-timestamp' => '2020-12-21 14:32:34',
)

# With client_ref
[2020-12-21 14:34:23] local.ERROR: array (
  'msisdn' => '1xxxxxxxxxx',
  'to' => '1xxxxxxxxxx',
  // ...
  'message-timestamp' => '2020-12-21 14:34:23',
)  
```

**Comment by driesvints** [comment]
Thanks for the PR!

**Comment by kodooy** [comment]
Thank you! Now it works perfectly :-)

**Comment by dragonmantank** [comment]
`client-ref` is definitely correct for SMS.

The `Vonage\Network\Number\Request` class is probably from an older API that's been long since deprecated (which I'll go through and get marked as such). That code hasn't been touched a long time, and from the looks of it was what turned into our Number Insights product. 

There's a really good chance no one noticed it was wrong just because most customers don't use `client-ref` at all.

**Comment by driesvints** [comment]
@dragonmantank thanks for the speedy answer Chris! :)
