### ISSUE TITLE
Upgrade nexmo/laravel

### ISSUE THREAD

**Issue by martio** [laravel/nexmo-notification-channel#54]
- Nexmo Notification Channel Version: 2.5.1
- Laravel Version: 8.82.0
- PHP Version: 8.1

### Description:

Please, upgrade `nexmo/laravel` to version `3.0.0`

For PHP 8.1:

```
Return type of Vonage\Client\Credentials\AbstractCredentials::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in vendor/vonage/client-core/src/Client/Credentials/AbstractCredentials.php on line 31
```

**Comment by driesvints** [comment]
We're currently preparing a new major version with v3 support of the core Vonage client here: https://github.com/laravel/nexmo-notification-channel/pull/53. I'm afraid that patching the current package to v3 of nexmo/laravel isn't an option, sorry.

**Comment by driesvints** [comment]
Hey @martio. Thanks to @SecondeJK there's now an update that adds the fixes for that: https://github.com/Vonage/vonage-php-sdk-core/releases/tag/2.10.1
