### ISSUE TITLE
Failed composer install

### ISSUE THREAD

**Issue by ejdelmonico** [laravel/nexmo-notification-channel#56]
- Vonage Notification Channel Version: 3.0.0
- Laravel Version: 9.0.2
- PHP Version: 8.1.2
- Database Driver & Version: mysql 8.0.28

### Description:

> sail composer require laravel/vonage-notification-channel:^3.0

./composer.json has been updated
Running composer update laravel/vonage-notification-channel
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - vonage/client-core[3.0.0, ..., 3.0.1] require psr/log ^1.1|^2.0 -> found psr/log[1.1.0, ..., 1.1.4, 2.0.0] but the package is fixed to 3.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - laravel/vonage-notification-channel[v3.0.0, ..., 3.x-dev] require vonage/client-core ^3.0 -> satisfiable by vonage/client-core[3.0.0, 3.0.1].
    - Root composer.json requires laravel/vonage-notification-channel ^3.0 -> satisfiable by laravel/vonage-notification-channel[v3.0.0, 3.x-dev].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

### Steps To Reproduce:

composer require laravel/vonage-notification-channel 

I beleive the issue is caused by the vonage/client-core requirements but I am not positive.

**Comment by ejdelmonico** [comment]
Temporary fix:

Install with the (-W) flag to downgrade psr/log (3.0.0 => 2.0.0). Laravel 9 uses psr/log 3.0.0 for initial installation but can use a previous version. The vonage/client-core is causing the issue due to a psr/log requirement of 1.0.0 or 2.0.0.

**Comment by driesvints** [comment]
Heya, thanks for letting us know. For now, indeed use v2. I've sent in a PR to the vonage core so hopefully that'll get merged and tagged soon 👍 

https://github.com/Vonage/vonage-php-sdk-core/pull/310
