### ISSUE TITLE
How to catch Vonage\\Client\\Exception\\Request in Laravel notifications

### ISSUE THREAD

**Issue by szepeviktor** [laravel/nexmo-notification-channel#58]
```php
Notification::send($users, new QuizStartedReminder($this->option('channel')));

// In QuizStartedReminder
return (new NexmoMessage)->content('Text of the message');
```

Please advise where/how to catch `Vonage\\Client\\Exception\\Request` in [Laravel](https://laravel.com/docs/8.x/notifications#sms-notifications).
Thank you.

Cc @iamgergo
Was https://github.com/Vonage/vonage-php-sdk-core/issues/267

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by szepeviktor** [comment]
Hello @driesvints!
The bug report is hidden in my question.
After an investigation I think the `Request` exception cannot be caught.
What do you think?
