### ISSUE TITLE
no api namespace found: message

### ISSUE THREAD

**Issue by ExpDev07** [laravel/nexmo-notification-channel#59]
- Vonage Notification Channel Version: ^3.0
- Laravel Version: 9.0
- PHP Version: 8.1
- Database Driver & Version:

### Description:

When trying to send SMS using Vonage, I get the `"no api namespace found: message"` error  on the VonageClient. I can see the cause of this is an update from 4 days ago: https://github.com/Vonage/vonage-php-sdk-core/commit/8ffaa3e8f589e4c8946bf972558283cf584bc360#diff-40d7473316ef0bb3ba4c4d937b16ae3d1cc47e0d65815034ee2b5be6a74cb11eL214.

**Comment by driesvints** [comment]
Seems like this is an issue with the core vonage client, not this library. They're aware and are going to address it. Thanks
