### ISSUE TITLE
Support sending to international numbers with nexmo.sms_from dynamic config

### ISSUE THREAD

**Issue by sts-ryan-holton** [laravel/nexmo-notification-channel#62]
Hi,

I'm using version 2.5.1 of the `nexmo-notification-channel` which I see is now known as the `vonage-notification-channel`. I'm based in the UK and have customers globally, I have set my `sms_from` to be the following:

```
'nexmo' => [
    'sms_from' => 'DomainMonit',
]
```

A change happened on 1st March 2022 beyond my control whereby sending to US numbers now requires the use of a toll-free number as described [here](https://api.support.vonage.com/hc/en-us/articles/204017023-US-SMS-Features-and-Restrictions).

Currently, my `sms_from` works perfectly fine for sending to UK based numbers, but, I'm going to need to buy a toll-free number, and somehow configure the `sms_from` to use the toll-free number for specific US customers (I have a column in my database I can utilise to get country), how can I change the `sms_from` dynamically to support this?

> All SMS sent to the US must originate from either a US pre-approved long number, registered toll-free, 10 DLC, or short code that is associated with your Vonage account. Alpha Sender IDs are not supported.

**Comment by driesvints** [comment]
I asked you several times to stop posting support questions on our issue trackers. Please refrain from doing so in the future.
