### ISSUE TITLE
Feature: Add more Channels (like WhatsApp)

### ISSUE THREAD

**Issue by pmochine** [laravel/nexmo-notification-channel#7]
Hey @all :)

This package adds more Channels: https://github.com/Nexmo/laravel-notification

Since this is the official package for Laravel, couldn't you add these functions as well:

- toNexmoWhatsApp
- toNexmoFacebook
- toNexmoViberServiceMessage
- toNexmoSms

**Comment by driesvints** [comment]
Heya. Since a third party package already supports these I don't think it makes much sense for us to add the same functionality to this one.

**Comment by pmochine** [comment]
@driesvints Ok, I understand! (I just don't like to use third-party packages, because sometimes they are too slow to update their dependencies etc.)
