### ISSUE TITLE
ErrorException: You are sending a message as `text` when contains unicode only  error thrown on 3.2.0

### ISSUE THREAD

**Issue by sts-ryan-holton** [laravel/nexmo-notification-channel#75]
- Vonage Notification Channel Version: 3.2.0
- Laravel Version: 9.51.0
- PHP Version: 8.2.x
- Database Driver & Version: MySQL 5.7

### Description:

I've just tried sending a text message,, the same exact message that I sent in the previous version of this package. I'm getting an `ErrorException` thrown by the Vonage library:

> ErrorException: You are sending a message as `text` when contains unicode only 
            characters. This could result in encoding problems with the target device or increased billing - See 
            https://developer.vonage.com/messaging/sms for details, or email support@vonage.com if you have any 
            questions. in /var/www/snapisms-api/vendor/vonage/client-core/src/SMS/Client.php:44

The message that I'm trying to send is:

> Another message [Sender: Ryan]

This previously worked, now fails as a failed job.

**Comment by dungnh** [comment]
I also getting this issue also. Hope someone can help.

**Comment by sts-ryan-holton** [comment]
@dungnh For now, I've had to rollback my version of this package.

Hopefully a solution/fix soon! 👍

**Comment by SecondeJK** [comment]
Will be a short turnaround for this, on it now.

**Comment by SecondeJK** [comment]
Release 4.0.6 of the Vonage SDK fixes the regex for this @sts-ryan-holton @dungnh

**Comment by SecondeJK** [comment]
The other issue here - that the Vonage SDK is firing a warning which is being turned into an Exception is a different problem. If something is picking up the `trigger_error` and converting it to an Exception, I'm tempted to either remove it altogether or get something like Monolog to put it in a logfile. I don't want to -stop- users from sending what they want to send, but I do want to warn them if it's the wrong encoding without an uncaught Exception stopping runtime.

**Comment by sts-ryan-holton** [comment]
@SecondeJK Thanks for this. Does this mean an update of this package won't be required? Maybe you can do some kind of config. In my system specifically I'm using a library to detect unicode characters and auto charge customers more credits per message.

**Comment by SecondeJK** [comment]
You can run composer update to pull the latest in.
The important thing here is that the underlying Vonage SDK can check the encoding for you.
`\Vonage\SMS\Message\SMS::isGsm7()` will give you back a boolean in order for you to decide whether to use Laravel's `unicode()`

**Comment by sts-ryan-holton** [comment]
Cool. So is your suggestion to wrap the part where I send a message in a `if` statement for this part of my code:

```php
try {
    $amount = $this->getNumberOfDeductableCredits($this->message->data['body']);
    $this->createCreditTransaction($message, $amount);

    return (new VonageMessage)
                ->clientReference($this->message->id)
                ->content($this->message->data['body']);

} catch (\Exception $e) { }
```

Something like...

```php
try {
    $amount = $this->getNumberOfDeductableCredits($this->message->data['body']);
    $this->createCreditTransaction($message, $amount);

    if (\Vonage\SMS\Message\SMS::isGsm7()) {
        return (new VonageMessage)
                ->clientReference($this->message->id)
                ->content($this->message->data['body'])
                ->unicode();
    }

    return (new VonageMessage)
                ->clientReference($this->message->id)
                ->content($this->message->data['body']);

} catch (\Exception $e) { }
```

**Comment by driesvints** [comment]
I guess the root issue here is resolved. Feel free to discuss further for anything else. Thanks
