### ISSUE TITLE
Error accessing the response data in the event listener

### ISSUE THREAD

**Issue by bhojkapderas** [laravel/nexmo-notification-channel#80]
### Vonage Notification Channel Version

2.5.1

### Laravel Version

8.83.27

### PHP Version

7.4

### Description

Having trouble accessing the response data from the event listener.

### Steps To Reproduce

`public function handle(NotificationSent $event)`

`$event->response` returns the class `Vonage\Message\Message`

So i figure i can get the data this way:

Running `$event->response->getResponseData()` i am getting this error

```
fseek() expects parameter 1 to be resource, int given {"exception":"[object] (ErrorException(code: 0): fseek() expects parameter 1 to be resource, int given at /home/vagrant/code/project/vendor/guzzlehttp/psr7/src/Stream.php:206)
[stacktrace]
#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 /home/vagrant/code/project/vendor/guzzlehttp/psr7/src/Stream.php(206): fseek()
#2 /home/vagrant/code/project/vendor/guzzlehttp/psr7/src/Stream.php(193): GuzzleHttp\\Psr7\\Stream->seek()
```

Is this a bug or is there a correct way to access the response data?

"laravel/framework": "^8.0",
"laravel/nexmo-notification-channel": "^2.5.1",

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!
