### ISSUE TITLE
STOP not working in NEXMO

### ISSUE THREAD

**Issue by pratiweb** [laravel/nexmo-notification-channel#81]
Hello 
One of my client using NEXMO api to send message from system using. There is facility to stop message send to client phone. 
After reply STOP message will not be stop and system still sending message

**Comment by crynobone** [comment]
Please use our bug report template and provide all the required information: https://github.com/laravel/vonage-notification-channel/issues/new?assignees=&labels=&projects=&template=1_Bug_report.yml
