### ISSUE TITLE
STOP not working in NEXMO

### ISSUE THREAD

**Issue by pratiweb** [laravel/nexmo-notification-channel#82]
### Vonage Notification Channel Version

"nexmo/laravel": "^2.4"

### Laravel Version

8.1

### PHP Version

8.1

### Database Driver & Version

5.7

### Description

One of my client using NEXMO api to send message from system. There is facility to stop message send to client phone.
After reply STOP message will not be stop and system still sending message

```
$neximoStatus =  (new NexmoMessage)
                ->content("Hi {$notifiable->name}, In 7 days the vaccine {$this->vaccine->name} is due to be administered {$this->textOnAnimal} {$this->textForDisease}. The administration date for this is {$this->alert->vaccinationDate()}. To opt out, please text reply STOP directly to this message.")
                ->from($from)
                ->unicode();
```
![unnamed](https://github.com/laravel/vonage-notification-channel/assets/37148199/63960389-3d4e-455e-97cd-12fbefe45f63)

### Steps To Reproduce

One of my client using NEXMO api to send message from system using. There is facility to stop message send to client phone.
After reply STOP message will not be stop and system still sending message

```
$neximoStatus =  (new NexmoMessage)
                ->content("Hi {$notifiable->name}, In 7 days the vaccine {$this->vaccine->name} is due to be administered {$this->textOnAnimal} {$this->textForDisease}. The administration date for this is {$this->alert->vaccinationDate()}. To opt out, please text reply STOP directly to this message.")
                ->from($from)
                ->unicode();
```

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!

**Comment by pratiweb** [comment]
@driesvints 
Are you asking to upgrade laravel of NEXMO library ?

**Comment by pratiweb** [comment]
@driesvints 
Are you supports STOP functionality ?
